services:
  - type: web
    name: url-shortener
    env: python
    buildCommand: pip install -r requirements.txt --no-cache-dir
    startCommand: gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
    autoDeploy: true
    healthCheckPath: /
    numInstances: 1
